# Specify version format
version: "{build}"

image: Visual Studio 2017

platform: x64

# specify custom environment variables
environment:
  MSVC_DEFAULT_OPTIONS: ON
  CMAKE_TOOLCHAIN_FILE: -DCMAKE_TOOLCHAIN_FILE="C:\tools\vcpkg\scripts\buildsystems\vcpkg.cmake"
  matrix:
    - CMAKE_GENERATOR: -G"Visual Studio 15 2017 Win64"
      CMAKE_TOOLCHAIN: -T"v141"

# build configuration, i.e. Debug, Release, etc.
configuration:
  - Debug
  - Release

# branches to build
branches:
  # blacklist
  except:
    - gh-pages

# scripts that run after cloning repository
install:
  - if "%platform%"=="Win32" set VCPKG_ARCH=x86-windows
  - if "%platform%"=="x64"   set VCPKG_ARCH=x64-windows

  # install pacakges
  - vcpkg install boost:%VCPKG_ARCH%
  - vcpkg install tiny-dnn:%VCPKG_ARCH%
  
  - vcpkg integrate install

  - cmd: cd C:\projects\dart
  - cmd: md build
  - cmd: cd build
  - cmd: cmake %CMAKE_GENERATOR% -DCMAKE_BUILD_TYPE=%configuration% -DDART_MSVC_DEFAULT_OPTIONS="%MSVC_DEFAULT_OPTIONS%" %CMAKE_TOOLCHAIN_FILE% %CMAKE_TOOLCHAIN% ..
  
# preserve contents of selected directories and files across project builds
cache:
  - C:\tools\vcpkg\installed -> .appveyor.yml
  
build_script:
  - mkdir build
  - cd build
  - cmake %CMAKE_GENERATOR% -DCMAKE_BUILD_TYPE=%configuration% %CMAKE_TOOLCHAIN_FILE% %CMAKE_TOOLCHAIN% ..
  - msbuild tiny-dnn-practice.sln
  - ctest
  - cd ..
